vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /uploads/products
            upload_destination: '%kernel.project_dir%/uploads/products'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        cars:
            uri_prefix: /uploads/cars
            upload_destination: '%kernel.project_dir%/uploads/cars'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
