services:
  web:
    build: .
    container_name: symfony-app-web
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - COMPOSER_VERSION=2
      - WEB_DOCUMENT_INDEX=public/index.php
    depends_on:
      - database
    ports:
      - "80:80"

###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.0.32}
    container_name: symfony-app-database
    environment:
      MYSQL_ROOT_PASSWORD: verySecret
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      # You should definitely change the password in production
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-!ChangeMe!}
      MYSQL_USER: ${MYSQL_USER:-app}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${MYSQL_PASSWORD}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
