name: Fix code styling

on: [push]

jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['8.3']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: php-cs-fixer:3.64

      - name: Run PHP-CS-Fixer
        run: php-cs-fixer fix --dry-run

  linters:
    name: Linters PHP
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['8.3']
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          extensions: intl
          php-version: ${{ matrix.php-version }}
          tools: composer:v2
  
      - name: Set composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer
        uses: actions/cache@v4
        with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
            restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --ansi --no-interaction --no-progress

      - name: Lint YAML files
        run: ./bin/console lint:yaml config --parse-tags

      - name: Lint Twig templates
        run: ./bin/console lint:twig templates --env=prod

      - name: Lint XLIFF translations
        run: ./bin/console lint:xliff translations

      - name: Lint Parameters and Services
        run: ./bin/console lint:container --no-debug

      - name: Lint Doctrine entities
        run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

      - name: Lint Composer config
        run: composer validate --strict

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze

  eslint:
    name: Linters JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run lint for JS and TS
        run: npm run lint

      - name: Clean up
        run: rm -rf node_modules