name: Fix code styling

on: [push]

jobs:
  php-linters:
    name: Linters PHP
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PHP with extensions
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          extensions: intl
          php-version: '8.3'

      - name: Set composer cache directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer
        uses: actions/cache@v4
        with:
            path: ${{ steps.composer-cache.outputs.dir }}
            key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
            restore-keys: ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --ansi --no-interaction --no-progress

      - name: Lint YAML files
        run: ./bin/console lint:yaml config --parse-tags

      - name: Lint Twig templates
        run: ./bin/console lint:twig templates --env=prod

      - name: Lint XLIFF translations
        run: ./bin/console lint:xliff translations

      - name: Lint Parameters and Services
        run: ./bin/console lint:container --no-debug

      - name: Lint Doctrine entities
        run: ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction

      - name: Lint Composer config
        run: composer validate --strict

      - name: Check if any dependencies are compromised
        run: composer audit

      - name: Run PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --dry-run

      - name: Run PHPStan
        run: ./vendor/bin/phpstan analyze

      - name: Run PHP Insights
        run: ./vendor/bin/phpinsights

  eslint:
    name: Linters JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run lint for JS and TS
        run: npm run lint
